sudo: required
language: cpp

services:
  - docker

before_install:
  - docker pull clarkp/test-env:v1.0
  - export DOCKER_RUN="docker run -v ${TRAVIS_BUILD_DIR}:/home/test/ clarkp/test-env:v1.0"

script:
  - ${DOCKER_RUN} /bin/bash -l -c "module load fftw openblas && module list && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib && autoreconf -f -i && ./configure && make"

notifications:
  email: false
